name: transfero
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bip39: ^1.0.6
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  ed25519_hd_key: ^2.2.0
  equatable: ^2.0.3
  fl_chart: ^0.45.0
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.2+1
  flutter_sticky_header: ^0.6.0
  google_fonts: ^2.3.1
  hex: ^0.2.0
  hive: ^2.0.6
  http: ^0.13.4
  motion_toast: ^2.1.1
  path_provider: ^2.0.9
  queue: ^3.1.0+1
  retry: ^3.1.0
  web3dart: ^2.3.5
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cryptos/
    - assets/TargaryenCoin.json
    - .env
